name: flutter_colorpicker
description: HSV(HSB)/HSL/RGB/Material color picker inspired by all the good design for your amazing flutter apps.
version: 1.1.5
homepage: https://github.com/mchome/flutter_colorpicker

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
